## Import data
```{r}
library(mgcv)
library(ggplot2)
library(vcd)
library(visreg)
df <- read.csv("~/Desktop/Data science/medical records/R/combined_firstpf_compliance.csv",na.strings = c(""))

df$mortality_num[df$hospitaldischargestatus=="Alive"]<-0
df$mortality_num[df$hospitaldischargestatus=="Expired"]<-1
df$icu_mortality[df$unitdischargestatus=="Alive"]<-0
df$icu_mortality[df$unitdischargestatus=="Expired"]<-1

# eliminate outliers
df$bmi[df$bmi>100 | df$bmi<10]<-NA
df$tidal_volume[df$tidal_volume>1000]<-NA
df$TV_IBW_calculated[df$TV_IBW_calculated<0]<-NA
df$TV_IBW_calculated[df$TV_IBW_calculated>20]<-NA
df$max_peep[df$max_peep>20]<-NA
df<-df[!is.na(df$mortality_num),]
```

Old
## Visual exploratory data analysis
```{r}
# Association of PF ratio and respiratory system compliance
par(mfrow=c(1,2))

model<-gam(lung_compliance ~ s(pfratio),data=df)
visreg(model, "pfratio",rug=TRUE,cex=0.25,band=TRUE,xlab=expression("PaO"[2]*"/FiO"[2]*"(mmHg)"),ylab=expression("C"[rs]*" ml/cmH"[2]*"O"),points=list(col="#55555540", cex=0.25)) 
modela<-gam(lung_compliance ~ s(pfratio)+pfratio+sofatotal+age+bmi,data=df)
visreg(modela, "pfratio",rug=TRUE,cex=0.25,band=TRUE,xlab=expression("PaO"[2]*"/FiO"[2]*"(mmHg)"),ylab=expression("C"[rs]*" ml/cmH"[2]*"O"),points=list(col="#55555540", cex=0.25)) 

summary(model)
summary(modela)

# Association of general additive model curve for hospital mortality versus the respiratory system compliance
# adjusted
model1 = gam(mortality_num ~ s(lung_compliance)+pfratio+age+bmi+sofatotal, data=df, family=binomial)
summary(model1)

# no adjustment
model1a = gam(mortality_num ~ s(lung_compliance), data=df, family=binomial)
summary(model1a)

par(mfrow=c(1,2))
visreg(model1a, "lung_compliance",scale="response", rug=2, xlab=expression("C"[rs]*" ml/cmH"[2]*"O"),ylab="Probability of dying",ylim = c(0,1))
visreg(model1, "lung_compliance",scale="response", rug=2, xlab=expression("C"[rs]*" ml/cmH"[2]*"O"),ylab="Probability of dying",ylim = c(0,1))
```


## Demographics
```{r}
install.packages("gmodels")
library(gmodels)
dfL<-df[df$compliance_level=="L",]
dfI<-df[df$compliance_level=="I",]
dfH<-df[df$compliance_level=="H",]

# Number of patients
# compliance distribution
table(df$compliance_level)

# Age
aggregate(x = df$age,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE))) 

# Gender
table(df$compliance_level)
table(df$gender, df$compliance_level)
round(table(dfL$gender)/sum(table(dfL$gender)),3) #0 NA
round(table(dfI$gender)/sum(table(dfI$gender)),3) #0 NA
round(table(dfH$gender)/sum(table(dfH$gender)),3) #0 NA

# BMI
aggregate(x = df$bmi,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE))) 

# SOFA score (SD)
aggregate(x = df$sofatotal,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE))) 

# Source of admission
round(table(dfL$unitAdmitSource)/sum(table(dfL$unitAdmitSource)),3)
round(table(dfI$unitAdmitSource)/sum(table(dfI$unitAdmitSource)),3)
round(table(dfH$unitAdmitSource)/sum(table(dfH$unitAdmitSource)),3)
```

## Comorbid conditions
```{r}
mat <- matrix(NA_character_, nrow = 11, ncol = 2,
              dimnames = list( c("AF","Cancer","CHF","CKD","CLD","COPD","DMD","hypertension","IHD","sepsis","stroke"),c("FALSE","TRUE")))

# Low elastance 
comorbid<-function(df){
mat[1,]<-round(table(df$has_atrial_fibrillation_disease)/sum(table(df$has_atrial_fibrillation_disease)),3)
mat[2,]<-round(table(df$has_cancer_disease)/sum(table(df$has_atrial_fibrillation_disease)),3)
mat[3,]<-round(table(df$CHF)/sum(table(df$CHF)),3)
mat[4,]<-round(table(df$CKD)/sum(table(df$CKD)),3)
mat[5,]<-round(table(df$has_chronic_liver_disease)/sum(table(df$has_chronic_liver_disease)),3)
mat[6,]<-round(table(df$has_copd_disease)/sum(table(df$has_copd_disease)),3)
mat[7,]<-round(table(df$has_diabetes_mellitus_disease)/sum(table(df$has_diabetes_mellitus_disease)),3)
mat[8,]<-round(table(df$has_hypertension_disease)/sum(table(df$has_hypertension_disease)),3)
mat[9,]<-round(table(df$has_ischemic_heart_disease)/sum(table(df$has_ischemic_heart_disease)),3)
mat[10,]<-round(table(df$has_sepsis)/sum(table(df$has_sepsis)),3)
mat[11,]<-round(table(df$has_stroke_disease)/sum(table(df$has_stroke_disease)),3)

return(mat)
}

comorbid(dfL)
comorbid(dfI)
comorbid(dfH)
```

## Vital signs on ICU admission
```{r}
# Temperature
aggregate(x = df$temperature,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE))) 

# Heart rate
aggregate(x = df$heartrate,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE))) 

# Mean arterial pressure
aggregate(x = df$mean_arterial_pressure,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE))) 

# Respiratory rate
aggregate(x = df$respiration,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))

```

## ARDS severity on ICU admission
```{r}
# ARDS severity on ICU admission
round(table(dfL$ARDS_severity)/sum(table(dfL$ARDS_severity)),3)
round(table(dfI$ARDS_severity)/sum(table(dfI$ARDS_severity)),3)
round(table(dfH$ARDS_severity)/sum(table(dfH$ARDS_severity)),3)
```

## Gas exchange parameters on ICU admission
```{r}
# PaO2
aggregate(x = df$pao2,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))
# PF ratio
aggregate(x = df$pfratio,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))

# PaCO2
aggregate(x = df$paco2,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))

# PH
aggregate(x = df$PH,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))
```

## Ventilator settings on ICU admission
```{r}
#FIO2
aggregate(x = df$fio2,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))

# Compliance median(IQR)
summary(dfL$lung_compliance)
summary(dfI$lung_compliance)
summary(dfH$lung_compliance)

# Mean plateau pressure (cmH2O) (SD)
aggregate(x = df$plateau_pressure,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))

# Mean PEEP (cmH2O) (SD)
aggregate(x = df$peep,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))

# Mean driving pressure (cmH2O) (SD)
df$driving_pressure<-df$plateau_pressure-df$peep
aggregate(x = df$driving_pressure,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))

# Mean tidal volume (ml) (SD)
aggregate(x = df$tidal_volume,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))

# Mean TV/kg IBW (ml/kg) (SD)
aggregate(x = df$TV_IBW_calculated,                
          by = list(df$compliance_level),              
          FUN=function(x) c(mn=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE)))
```

## Patient outcomes
```{r}
# Median duration of mechanical ventilation (days) (IQR)
summary(dfL$vent_duration)/24
summary(dfI$vent_duration)/24
summary(dfH$vent_duration)/24

# Median duration of ICU stay (days) (IQR)
summary(dfL$unit_duration)/60/24
summary(dfI$unit_duration)/60/24
summary(dfH$unit_duration)/60/24

# Median duration of hospital stay (days) (IQR)
summary(dfL$hospital_duration)/60/24
summary(dfI$hospital_duration)/60/24
summary(dfH$hospital_duration)/60/24

# ICU mortality (%)
round(table(dfL$unitdischargestatus)/sum(table(dfL$unitdischargestatus)),3)
round(table(dfI$unitdischargestatus)/sum(table(dfI$unitdischargestatus)),3)
round(table(dfH$unitdischargestatus)/sum(table(dfH$unitdischargestatus)),3)

chisq.test(table(df$unitdischargestatus,df$compliance_level),correct = FALSE)

# Hospital mortality (%)
round(table(dfL$hospitaldischargestatus)/sum(table(dfL$hospitaldischargestatus)),3)
round(table(dfI$hospitaldischargestatus)/sum(table(dfI$hospitaldischargestatus)),3)
round(table(dfH$hospitaldischargestatus)/sum(table(dfH$hospitaldischargestatus)),3)

chisq.test(table(df$hospitaldischargestatus,df$compliance_level),correct = FALSE)
```

## Odds ratio
```{r}
df$compliance_level<-factor(df$compliance_level,levels=c("L","I","H"))

model4= glm(mortality_num ~ df$compliance_level, data=df, family=binomial)
exp(cbind(OR = coef(model4), confint(model4)))

model4a = glm(mortality_num ~compliance_level+ pfratio+age+bmi+sofatotal, data=df, family=binomial)
exp(cbind(OR = coef(model4a), confint(model4a)))

model5= glm(icu_mortality ~ compliance_level, data=df, family=binomial)
exp(cbind(OR = coef(model5), confint(model5)))

model5a = glm(icu_mortality ~compliance_level+ pfratio+age+bmi+sofatotal, data=df, family=binomial)
exp(cbind(OR = coef(model5a), confint(model5a)))
```

## Check how each of the 4 compliance groups shift across time
```{r}
df1 <- read.csv("day12.csv")
df1<-df1[c(4,5)]
table(df1)

# transition matrix
trans.matrix <- function(X, prob=T)
{
  tt <- table( c(X[,-ncol(X)]), c(X[,-1]) )
  if(prob) tt <- round(tt / rowSums(tt))
  tt
}
transition<-trans.matrix(df1)

```

Transition mortality
```{r}
df1 <- read.csv("day12.csv")
table(df1$day1_compliance,df1$hospitaldischargestatus)

transition<-function(day1,day2){
  transition1<-df1[df1$day1_compliance==day1 & df1$day2_compliance==day2,]
  table2<-table(transition1$hospitaldischargestatus)
  mortality<-round(table2["Expired"]/sum(table2),3)
  result1 = paste(day1,day2,"; Mortality:",mortality,"; Number of patients:",table2["Expired"],"/",sum(table2),sep=" ")
  print(result1)
  avg<-round(mean(transition1$pfratio),3)
  result2 = paste("; Mean Pf ratio:",avg,sep=" ")
  print(result2)
}

transition("Type L","Type L")
transition("Type L","Intermediate phenotype")
transition("Type L","Type H")
transition("Intermediate phenotype","Type L")
transition("Intermediate phenotype","Intermediate phenotype")
transition("Intermediate phenotype","Type H")
transition("Type H","Type L")
transition("Type H","Intermediate phenotype")
transition("Type H","Type H")

# transit to type L
chisq.test(cbind(c(10,43),c(32,103)),corr=F)
chisq.test(cbind(c(13,58),c(32,103)),corr=F)

# transit to Intermediate
chisq.test(cbind(c(3,28),c(68,212)),corr=F)
chisq.test(cbind(c(15,72),c(68,212)),corr=F)

# transit to type H
chisq.test(cbind(c(2,17),c(272,907)),corr=F)
chisq.test(cbind(c(19,75),c(272,907)),corr=F)


data<-df1[df1$day1_compliance=="Type L" & df1$day2_compliance=="Type L",]
data2<-df1[df1$day1_compliance=="Type L" & df1$day2_compliance=="Intermediate phenotype",]
data3<-df1[df1$day1_compliance=="Type L" & df1$day2_compliance=="Type H",]

t.test(data$pfratio,data3$pfratio)
t.test(data2$pfratio,data3$pfratio)

data4<-df1[df1$day1_compliance=="Intermediate phenotype" & df1$day2_compliance=="Type L",]
data5<-df1[df1$day1_compliance=="Intermediate phenotype" & df1$day2_compliance=="Intermediate phenotype",]
data6<-df1[df1$day1_compliance=="Intermediate phenotype" & df1$day2_compliance=="Type H",]

t.test(data4$pfratio,data6$pfratio)
t.test(data5$pfratio,data6$pfratio)

data7<-df1[df1$day1_compliance=="Type H" & df1$day2_compliance=="Type L",]
data8<-df1[df1$day1_compliance=="Type H" & df1$day2_compliance=="Intermediate phenotype",]
data9<-df1[df1$day1_compliance=="Type H" & df1$day2_compliance=="Type H",]

t.test(data7$pfratio,data9$pfratio)
t.test(data8$pfratio,data9$pfratio)

```

